### ISSUE TITLE
asg.actions.detach_random_instances: also return IDs of detached instances

### ISSUE THREAD

**Issue by anukul** [chaostoolkit-incubator/chaostoolkit-aws#105]
Referring to [asg.actions.detach_random_instances](https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/0.16.0/chaosaws/asg/actions.py#L351), expected similar behavior to other `.*_random_.*` actions that return IDs of the randomly selected resources, such as:
- [asg.actions.terminate_random_instances](https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/0.16.0/chaosaws/asg/actions.py#L95)
- [asg.actions.stop_random_instances](https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/0.16.0/chaosaws/asg/actions.py#L180)
- [asg.actions.detach_random_volume](https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/0.16.0/chaosaws/asg/actions.py#L391)
- [ecs.actions.stop_random_tasks](https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/0.16.0/chaosaws/ecs/actions.py#L70)

**Comment by anukul** [comment]
Happy to make a PR if this request makes sense! :)

**Comment by Lawouach** [comment]
Hey there,

Good catch. Would that change be additive only you think? If so, please go ahead with a PR :)

**Comment by anukul** [comment]
@Lawouach yes, the PR should not break any existing flow.
