### ISSUE TITLE
There is no way to configure http proxies

### ISSUE THREAD

**Issue by kgangerlm** [chaostoolkit-incubator/chaostoolkit-aws#141]
Most enterprises have an http proxy between their network and the internet.  In order to talk to the aws api traffic must pass though this proxy.  boto3 is not respecting the standard environment variables for proxy settings.  I was able to get my experiments to work by adding the following code to the aws_client creation code.  

```python
      from botocore.config import Config
        if "http_proxy" in os.environ and "https_proxy" in os.environ:
            params["config"] = Config(proxies={
                "http": os.environ["http_proxy"],
                "https": os.environ["https_proxy"],
            })
```

If you are okay with this change I can clean it up and submit a pull request.

**Comment by ciaranevans** [comment]
Seems sensible to me. I'm sure the PR would be appreciated!
