### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by 0rc** [chaostoolkit-incubator/chaostoolkit-aws#29]
Hi guys,

do you mind releasing new version with my latest changes? 0.7.2 or whatever you think is better

thanks,

**Comment by Lawouach** [comment]
Hey @0rc ,

Sorry for the delay and you did right pinging us!

[0.8.0](https://pypi.org/project/chaostoolkit-aws/0.8.0/) is now out :)

Thanks for all the hard work!

- Sylvain
