### ISSUE TITLE
Error while executing chaos commands 

### ISSUE THREAD

**Issue by mittachaitu** [chaostoolkit-incubator/chaostoolkit-aws#36]
Followed https://docs.chaostoolkit.org/reference/usage/install/ document to install chaostoolkit. After installation, while executing chaos CLI commands facing error 
```
(chaostk) root@9a0dbb329757:/# chaos --version
Traceback (most recent call last):
  File "/root/.venvs/chaostk/bin/chaos", line 7, in <module>
    from chaostoolkit.__main__ import cli
  File "/root/.venvs/chaostk/lib/python3.5/site-packages/chaostoolkit/__main__.py", line 2, in <module>
    from chaostoolkit.cli import cli
  File "/root/.venvs/chaostk/lib/python3.5/site-packages/chaostoolkit/cli.py", line 9, in <module>
    from typing import List, NoReturn
ImportError: cannot import name 'NoReturn'
```

**Comment by Lawouach** [comment]
Hey, do you mind if I move this issue to the chaostoolkit repo? It's indeed a bug because NoReturn only came with Python 3.6.5.

**Comment by mittachaitu** [comment]
> Hey, do you mind if I move this issue to the chaostoolkit repo? It's indeed a bug because NoReturn only came with Python 3.6.5.

@Lawouach yeah sure, you can move it to the corresponding repo.

**Comment by Lawouach** [comment]
Damn, we can't move cross-organizations. Stupid GitHUb :p

**Comment by Lawouach** [comment]
I've created https://github.com/chaostoolkit/chaostoolkit/issues/90 to cover it.

I'll close this one now :)
