### ISSUE TITLE
Assume arn role

### ISSUE THREAD

**Issue by cara-puce** [chaostoolkit-incubator/chaostoolkit-aws#5]
Hi guys,

I can't manage to assume a specific role when i launch my chaos experiment.
I'd set up my config & credentials files correctly since I can assume the role when I use aws client.

Any ideas?

Thx,

**Comment by cara-puce** [comment]
[Update]
I managed to do it by setting AWS_PROFILE environment variable but this is not so comfortable.
Is there a way to do it directly in chaos-toolkit ?

Thx,

**Comment by Lawouach** [comment]
Hi @cara-puce,

I am sure there is a way but I haven't played with it yet, I will try next week and add a fix.

Cheers,

**Comment by cara-puce** [comment]
Ok, great thanks :)

FYI, What I've tried and why I think it didn't work : 
- Add "profile_name" in "secrets.aws". _Didn't work because only session_token, access_key and key_id are retrieved from it and used as credentials._
- Add "profile_name" in "configuration". _Didn't work because credentials things shouldn't set in there (says the documentation)._

**Comment by Lawouach** [comment]
Great feedback! I'm gonna work on that this week and will release asap.

**Comment by Lawouach** [comment]
Just wanted to clarify, as we're using boto3 under the hood, could you confirm which of the followings you are keen on?

- https://boto3.readthedocs.io/en/latest/guide/configuration.html#assume-role-provider
- https://boto3.readthedocs.io/en/latest/guide/configuration.html#iam-role

So I can be sure to implement the right one (I assume it's the first one.)

**Comment by Lawouach** [comment]
Or, more likely this one:

> You can then specify a profile name via the AWS_PROFILE environment variable or the profile_name argument when creating a Session:

You can then specify a profile name via the AWS_PROFILE environment variable or the profile_name argument when creating a Session:

**Comment by Lawouach** [comment]
Odd, boto3 client signature doesn't include a profile_name either https://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.client

**Comment by cara-puce** [comment]
Yep, first one but bypassed it with third one!

**Comment by Lawouach** [comment]
Do you think you could try that branch and see if that works out please?

**Comment by cara-puce** [comment]
Of course, I'll let you know!

**Comment by cara-puce** [comment]
Ok, it seems to work!
Great work, thanks a lot!
