### ISSUE TITLE
Security group rules modification available

### ISSUE THREAD

**Issue by insider89** [chaostoolkit-incubator/chaostoolkit-aws#76]
As I see, you've added ability to modify EC2 security group, but didn't add tag 0.14.0, in which they should be available. Any concern to not add 0.14.0 tag? I want to make an experiment with blocking access via SG. If it is possible, please bump version to 0.14.0.

**Comment by simontabor** [comment]
We currently have 0.0.14 in the CHANGELOG.md (added by https://github.com/chaostoolkit-incubator/chaostoolkit-aws/commit/c105a155950e5a93d0bcb50400354bafab665927) but no tag was ever created.

Should updating CHANGELOG.md be an automatic part of the release process to avoid issues like this?
