### ISSUE TITLE
Project health

### ISSUE THREAD

**Issue by simontabor** [chaostoolkit-incubator/chaostoolkit-aws#83]
👋   it looks as if the last commit to this repo was 12th May, with the last release made on 26th March, leaving issues like #76 unanswered.

There are also a few things I'd suggest setting up to keep this project active:

1. Add a maintainers section to the README - if there are no active maintainers then add a notice saying maintainers wanted!
2. `.github/CODEOWNERS` to request reviews from the maintainers on PRs
3. `CONTRIBUTING.md` with a quick guide to contributing (can mostly be taken from https://github.com/chaostoolkit-incubator/chaostoolkit-aws#contribute)
4. PR + Issue template to speed up bug triage and reviews
5. Code of conduct
6. GitHub Project to track issues/roadmap/reviews - could we jump on https://github.com/orgs/chaostoolkit/projects/5? Or are incubator projects unable to be tracked on the main project? #23 

Most of these issues seem to affect all chaostoolkit (incubator and main) projects - is there a template that they were all taken from?

I'd be happy to help out wherever needed - let me know your thoughts!

**Comment by Lawouach** [comment]
Hello @simontabor, these are very good points.

We do need to think for the future when it comes to the governance of haos Toolkit and its satellites projects. There had been a nucleaus of discussion at https://github.com/chaostoolkit/chaostoolkit/issues/75.

I need to figure out how to bootstrap the whole thing so we can finally move on to a proper way of governing Chaos Toolkit.
