### ISSUE TITLE
Ensure actions to be really successfully completed

### ISSUE THREAD

**Issue by Xat59** [chaostoolkit-incubator/chaostoolkit-aws#96]
The current behavior when running actions is to ensure the API call has been successful and is valid.

It could be fine to have a behavior that wait the actions to be successfully completed before re-run the second check.

Imagine in your actions you want to stop a DB instance using ```stop_db_instance``` or stop a standard ec2 instance using ```stop_instance```.

Because the second steady state check is executed immediately after actions, the instance is not yet stopped. And it results the second check successfully while the instance is actually stopping.

```
$ aws rds describe-db-instances --db-instance-identifier rds-foo|grep DBInstanceStatus
"DBInstanceStatus": "stopping",
```

We could use ```pauses``` in the action to wait some time the instance is completely stopped, but that is not ideal for reasons. In my case, the DB instance takes around 10 minutes to be with a **real** ```stopped``` state.

I think (in the case of an RDS instance), it would be better to check ```DBInstanceStatus``` is ```stopped``` before running the second check phase.

I guess that behavior affects a bunch of actions.
What do you think about it ?

**Comment by Lawouach** [comment]
I'm not a user of this extensions so I don't want to presume too much but this makes a lot of sense to me.

wdyt @joshuaroot?

**Comment by joshuaroot** [comment]
I don't know, this could be solved by simply applying a `pauses: {after: 600}` to the action, couldn't it?

Also, regarding the hypothesis failing, if you're tolerance is `stopped` it's going to fail prior to even getting to actions as the RDS or EC2 is `running`, yes?
